### ISSUE TITLE
Segfault when trying to use `tree.ITree` with `pebble.ProcessPool.map` (multiprocessing)

### ISSUE THREAD

**Issue by NiklasBeierl** [mikpom/rbi_tree#4]
Hello,

I have to perform a huge amount of lookups on a tree and I figured I would parallelize it using [pebble](https://pythonhosted.org/Pebble/) (Which is basically just a convenient wrapper around `multiprocessing` ).
First thing I did was just hand all the "intervals" for my tree to every process, along with the a subset of the lookups.
Then every process would build his own `ITree`, perform the lookups (`find_at` ) I gave him, return the results and I would gather the results together in the "main" process. That worked.

Now, as far as I understood, whenever I can `pickle` something, I can send it to a subprocess. Since I was successfully able to pickle and unpickle a tiny `ITree` instance, (3 intervals) I figured I could build the tree only once and then hand it to all of the subprocesses so they could go straight for the lookups. But that caused segfaults:

```
[63024.464703] python[33374]: segfault at 7f1948afb990 ip 00007f193ace6b98 sp 00007ffe3ea97aa0 error 6 in tree.cpython-39-x86_64-linux-gnu.so[7f193acdd000+12000]
[63024.464710] Code: c6 02 00 00 48 8b 5c 24 20 48 8b 44 24 28 31 ff 48 39 c3 0f 84 cf 00 00 00 8b 4c 24 14 39 4b 04 0f 84 b5 00 00 00 4c 8b 63 08 <49> 83 04 24 01 48 85 ff 74 0a 48 83 2f 01 0f 84 c4 00 00 00 48 63
[63024.464750] audit: type=1701 audit(1621677928.571:446): auid=1000 uid=1000 gid=1000 ses=5 pid=33374 comm="python" exe="/usr/bin/python3.9" sig=11 res=1
[63024.491981] audit: type=1334 audit(1621677928.601:447): prog-id=96 op=LOAD
[63024.492094] audit: type=1334 audit(1621677928.601:448): prog-id=97 op=LOAD
[63024.492173] audit: type=1334 audit(1621677928.601:449): prog-id=98 op=LOAD
[63024.492731] audit: type=1130 audit(1621677928.601:450): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@22-33383-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[63027.508794] python[33373]: segfault at 7f1948aec510 ip 00007f193ace6b98 sp 00007ffe3ea97aa0 error 6 in tree.cpython-39-x86_64-linux-gnu.so[7f193acdd000+12000]
[63027.508802] Code: c6 02 00 00 48 8b 5c 24 20 48 8b 44 24 28 31 ff 48 39 c3 0f 84 cf 00 00 00 8b 4c 24 14 39 4b 04 0f 84 b5 00 00 00 4c 8b 63 08 <49> 83 04 24 01 48 85 ff 74 0a 48 83 2f 01 0f 84 c4 00 00 00 48 63
[63027.508850] audit: type=1701 audit(1621677931.618:451): auid=1000 uid=1000 gid=1000 ses=5 pid=33373 comm="python" exe="/usr/bin/python3.9" sig=11 res=1
[63027.514548] audit: type=1334 audit(1621677931.621:452): prog-id=99 op=LOAD
[63027.514617] audit: type=1334 audit(1621677931.621:453): prog-id=100 op=LOAD
[63030.625092] show_signal_msg: 2 callbacks suppressed
[63030.625094] python[33372]: segfault at 7f1948ae9930 ip 00007f193ace6b98 sp 00007ffe3ea97aa0 error 6 in tree.cpython-39-x86_64-linux-gnu.so[7f193acdd000+12000]
[63030.625101] Code: c6 02 00 00 48 8b 5c 24 20 48 8b 44 24 28 31 ff 48 39 c3 0f 84 cf 00 00 00 8b 4c 24 14 39 4b 04 0f 84 b5 00 00 00 4c 8b 63 08 <49> 83 04 24 01 48 85 ff 74 0a 48 83 2f 01 0f 84 c4 00 00 00 48 63
[63030.625160] audit: type=1701 audit(1621677934.735:456): auid=1000 uid=1000 gid=1000 ses=5 pid=33372 comm="python" exe="/usr/bin/python3.9" sig=11 res=1
[63030.630716] audit: type=1334 audit(1621677934.738:457): prog-id=102 op=LOAD
[63030.630843] audit: type=1334 audit(1621677934.738:458): prog-id=103 op=LOAD
[63030.630931] audit: type=1334 audit(1621677934.738:459): prog-id=104 op=LOAD
[63030.648436] audit: type=1130 audit(1621677934.758:460): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@24-33387-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[63033.771801] python[33376]: segfault at 7f1948afbb10 ip 00007f193ace6b98 sp 00007ffe3ea97aa0 error 6 in tree.cpython-39-x86_64-linux-gnu.so[7f193acdd000+12000]
[63033.771811] Code: c6 02 00 00 48 8b 5c 24 20 48 8b 44 24 28 31 ff 48 39 c3 0f 84 cf 00 00 00 8b 4c 24 14 39 4b 04 0f 84 b5 00 00 00 4c 8b 63 08 <49> 83 04 24 01 48 85 ff 74 0a 48 83 2f 01 0f 84 c4 00 00 00 48 63
[63033.771863] audit: type=1701 audit(1621677937.882:461): auid=1000 uid=1000 gid=1000 ses=5 pid=33376 comm="python" exe="/usr/bin/python3.9" sig=11 res=1
[63033.777281] audit: type=1334 audit(1621677937.885:462): prog-id=105 op=LOAD
[63033.777343] audit: type=1334 audit(1621677937.885:463): prog-id=106 op=LOAD
[63036.949930] show_signal_msg: 2 callbacks suppressed
[63036.949933] python[33378]: segfault at 7f1948aef7b0 ip 00007f193ace6b98 sp 00007ffe3ea97aa0 error 6 in tree.cpython-39-x86_64-linux-gnu.so[7f193acdd000+12000]
[63036.949939] Code: c6 02 00 00 48 8b 5c 24 20 48 8b 44 24 28 31 ff 48 39 c3 0f 84 cf 00 00 00 8b 4c 24 14 39 4b 04 0f 84 b5 00 00 00 4c 8b 63 08 <49> 83 04 24 01 48 85 ff 74 0a 48 83 2f 01 0f 84 c4 00 00 00 48 63
[63036.949963] audit: type=1701 audit(1621677941.058:466): auid=1000 uid=1000 gid=1000 ses=5 pid=33378 comm="python" exe="/usr/bin/python3.9" sig=11 res=1
[63036.955589] audit: type=1334 audit(1621677941.065:467): prog-id=108 op=LOAD
[63036.955649] audit: type=1334 audit(1621677941.065:468): prog-id=109 op=LOAD
[63036.955674] audit: type=1334 audit(1621677941.065:469): prog-id=110 op=LOAD
[63036.978185] audit: type=1130 audit(1621677941.088:470): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@26-33391-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[63039.972580] python[33377]: segfault at 7f18aa55ad50 ip 00007f193ace6b98 sp 00007ffe3ea97aa0 error 6 in tree.cpython-39-x86_64-linux-gnu.so[7f193acdd000+12000]
[63039.972587] Code: c6 02 00 00 48 8b 5c 24 20 48 8b 44 24 28 31 ff 48 39 c3 0f 84 cf 00 00 00 8b 4c 24 14 39 4b 04 0f 84 b5 00 00 00 4c 8b 63 08 <49> 83 04 24 01 48 85 ff 74 0a 48 83 2f 01 0f 84 c4 00 00 00 48 63
[63039.972639] audit: type=1701 audit(1621677944.082:471): auid=1000 uid=1000 gid=1000 ses=5 pid=33377 comm="python" exe="/usr/bin/python3.9" sig=11 res=1
[63039.978425] audit: type=1334 audit(1621677944.088:472): prog-id=111 op=LOAD
[63039.978515] audit: type=1334 audit(1621677944.088:473): prog-id=112 op=LOAD
[63043.098348] show_signal_msg: 2 callbacks suppressed
[63043.098350] python[33375]: segfault at 7f194d7760f0 ip 00007f193ace6b98 sp 00007ffe3ea97aa0 error 6 in tree.cpython-39-x86_64-linux-gnu.so[7f193acdd000+12000]
[63043.098358] Code: c6 02 00 00 48 8b 5c 24 20 48 8b 44 24 28 31 ff 48 39 c3 0f 84 cf 00 00 00 8b 4c 24 14 39 4b 04 0f 84 b5 00 00 00 4c 8b 63 08 <49> 83 04 24 01 48 85 ff 74 0a 48 83 2f 01 0f 84 c4 00 00 00 48 63
[63043.098382] audit: type=1701 audit(1621677947.208:476): auid=1000 uid=1000 gid=1000 ses=5 pid=33375 comm="python" exe="/usr/bin/python3.9" sig=11 res=1
[63043.104197] audit: type=1334 audit(1621677947.212:477): prog-id=114 op=LOAD
[63043.104201] audit: type=1334 audit(1621677947.212:478): prog-id=115 op=LOAD
[63043.104202] audit: type=1334 audit(1621677947.212:479): prog-id=116 op=LOAD
[63043.148079] audit: type=1130 audit(1621677947.258:480): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@28-33395-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[63046.069668] python[33379]: segfault at 7f1948b5cf90 ip 00007f193ace6b98 sp 00007ffe3ea97aa0 error 6 in tree.cpython-39-x86_64-linux-gnu.so[7f193acdd000+12000]
[63046.069677] Code: c6 02 00 00 48 8b 5c 24 20 48 8b 44 24 28 31 ff 48 39 c3 0f 84 cf 00 00 00 8b 4c 24 14 39 4b 04 0f 84 b5 00 00 00 4c 8b 63 08 <49> 83 04 24 01 48 85 ff 74 0a 48 83 2f 01 0f 84 c4 00 00 00 48 63
```
Corresponding python exception:
```
Traceback (most recent call last):
<Redacted>
    result = list(result.result())
  File "/home/niklas/code/remotes/anubis/nosyms/.venv/lib/python3.9/site-packages/pebble/pool/base_pool.py", line 209, in next
    raise result
  File "/home/niklas/code/remotes/anubis/nosyms/.venv/lib/python3.9/site-packages/pebble/pool/base_pool.py", line 232, in chunk_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
pebble.common.ProcessExpired: Abnormal termination
```

**Comment by mikpom** [comment]
Hi @NiklasBeierl .

I was unable to reproduce the problem on the following toy example. How reproducible is the error in your setup?


```
from pebble import ProcessPool
from rbi_tree.tree import ITree
t = ITree()
for i, int in enumerate([(1,3),(5,9),(6,10)]):
    t.insert(*int, i)

def find_at(v):
    return t.find_at(v)

with ProcessPool(max_workers=2) as pool:
    future = pool.map(find_at, range(10))
    for n in future.result():
        print(n)

```

**Comment by NiklasBeierl** [comment]
I used your example and took it closer to my original code, it seems that the segfault only occurs if I scale up a little and add `functools.partial` in the mix:
```
from pebble import ProcessPool
from multiprocessing import cpu_count
from rbi_tree.tree import ITree
from functools import partial

# num_intervals = 100 # Works, even with partial
# num_intervals = 1000 # Hangs with partial, works without partial
# num_intervals = 10000  # Segfaults with partial, works without partial
num_intervals = 1000000  # Segfaults with partial, works without partial

t = ITree()
for i, int in enumerate(zip(range(num_intervals), range(2, num_intervals + 2))):
    t.insert(*int, i)


def find_at(v):
    return t.find_at(v)


def find_at_partial(tree, v):
    return tree.find_at(v)


with_partial = True

with ProcessPool(cpu_count()) as pool:
    if with_partial:
        future = pool.map(partial(find_at_partial, t), range(10))
    else:
        future = pool.map(find_at, range(10))

    for n in future.result():
        print(n)
```

**Comment by mikpom** [comment]
Greetings!

I think i found the problem.

Could you please try version rbi-tree==0.1.3.2.dev1  in your setting?

Thanks,
Mikhail

**Comment by NiklasBeierl** [comment]
Heyya, sorry for the late reply, busy week. Yes it works in my setting as well. Thank you!
